const dummyData = [
  {
    CDRank: 1,
    college: "IIT Madras",
    ownership: "Public",
    coursesOffered: ["B.Tech", "M.Tech"],
    placementAverage: 2148000,
    placementHighest: 1980000,
    userReviews: 7.6,
    userReviewCount: 289,
    fees: 209550,
    location: "Chennai, Tamil Nadu",
    rankIndia: 3,
    logo: "/logos/madras.png",
  },
  {
    CDRank: 2,
    college: "IIT Delhi",
    ownership: "Public",
    coursesOffered: ["B.Tech", "M.Tech"],
    placementAverage: 2582000,
    placementHighest: 2000000,
    userReviews: 7.7,
    userReviewCount: 485,
    fees: 254650,
    location: "New Delhi, Delhi",
    rankIndia: 1,
    logo: "/logos/delhi.png",
  },
  {
    CDRank: 3,
    college: "Parul University",
    ownership: "Private",
    coursesOffered: ["B.Tech", "MBA"],
    placementAverage: 400000,
    placementHighest: 3000000,
    userReviews: 4.1,
    userReviewCount: 802,
    fees: 149000,
    location: "Vadodara, Gujarat",
    rankIndia: 99,
    logo: "/logos/parul.png",
    featured: true,
  },
  {
    CDRank: 4,
    college: "IIT Bombay",
    ownership: "Public",
    coursesOffered: ["B.Tech", "M.Tech"],
    placementAverage: 2182000,
    placementHighest: 3670000,
    userReviews: 8.1,
    userReviewCount: 306,
    fees: 229300,
    location: "Mumbai, Maharashtra",
    rankIndia: 2,
    logo: "/logos/mumbai.png",
  },
  {
    CDRank: 5,
    college: "IIT Roorkee",
    ownership: "Public",
    coursesOffered: ["B.Tech", "M.Tech"],
    placementAverage: 2112000,
    placementHighest: 3070000,
    userReviews: 8.2,
    userReviewCount: 308,
    fees: 229300,
    location: "Roorkee, Jharkhand",
    rankIndia: 12,
    logo: "/logos/roorkee1.png",
  },
  {
    CDRank: 6,
    college: "IIT Kharagpur",
    ownership: "Public",
    coursesOffered: ["B.Tech", "M.Tech"],
    placementAverage: 2982000,
    placementHighest: 3980000,
    userReviews: 8.3,
    userReviewCount: 366,
    fees: 229300,
    location: "Kharagpur, West Bengal",
    rankIndia: 9,
    logo: "/logos/Kharagpur.png",
  },
  {
    CDRank: 7,
    college: "IIT BHU",
    ownership: "Public",
    coursesOffered: ["B.Tech", "M.Tech"],
    placementAverage: 2199000,
    placementHighest: 3990000,
    userReviews: 8.4,
    userReviewCount: 376,
    fees: 229300,
    location: "Varanasi, UttarPradesh",
    rankIndia: 8,
    logo: "/logos/bhu.png",
  },
  {
    CDRank: 8,
    college: "IIT Bhilai",
    ownership: "Public",
    coursesOffered: ["B.Tech", "M.Tech"],
    placementAverage: 2122000,
    placementHighest: 3270000,
    userReviews: 8.5,
    userReviewCount: 396,
    fees: 229300,
    location: "Bhilai, Chattisgarh",
    rankIndia: 7,
    logo: "/logos/bhilai.png",
  },
  {
    CDRank: 9,
    college: "IIT Dhanbad",
    ownership: "Public",
    coursesOffered: ["B.Tech", "M.Tech"],
    placementAverage: 2112000,
    placementHighest: 3500000,
    userReviews: 7.8,
    userReviewCount: 392,
    fees: 229300,
    location: "Dhanbad, Jharkhand",
    rankIndia: 6,
    logo: "/logos/dhanbad.png",
  },
  {
    CDRank: 10,
    college: "IIT Kanpur",
    ownership: "Public",
    coursesOffered: ["B.Tech", "M.Tech"],
    placementAverage: 2172000,
    placementHighest: 3660000,
    userReviews: 8.7,
    userReviewCount: 331,
    fees: 229100,
    location: "Kanpur, UttarPradesh",
    rankIndia: 5,
    logo: "/logos/Kanpur.png",
  },
];

export default dummyData;
